[package]
name = "virtblocks_rust_native"
version = "0.1.0"
authors = ["Andrea Bolognani <abologna@redhat.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
errno = "0.2"
closefds = { git = "https://github.com/virtblocks/closefds", branch = "virtblocks" }

[lib]
crate-type = ["lib"]
